apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eric-pm-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eric-pm-server
subjects:
- kind: ServiceAccount
  name: eric-pm-server
  namespace: {{ .Release.Namespace }}
