### Requires service endpoint access for init wait container
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
  labels:
    app: enm-default
  name: enm-default
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - anyuid
{{- if .Values.global.sccResources }}
{{- toYaml .Values.global.sccResources | nindent 6}}
{{- end }}
  - apiGroups:
      - ""
    resources:
      - endpoints
      - services
    verbs:
      - get
      - list
      - watch
