### neo4j uses tini
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: enm-priviliged-policy-neo4j-graph
  labels:
  annotations:
roleRef:
  kind: Role
  name: enm-default
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: neo4j-sa
---
### neo4j uses tini
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: enm-priviliged-policy-neo4j-graph-load
  labels:
  annotations:
roleRef:
  kind: Role
  name: enm-default
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: default
---
### elasticsearch
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: enm-priviliged-policy-elasticsearch
  labels:
  annotations:
roleRef:
  kind: Role
  name: enm-default
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: elasticsearch-sa
