apiVersion: v1
kind: ServiceAccount
metadata:
  name: eric-pm-server
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
